### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'capture_output'

### ISSUE THREAD

**Issue by Chew** [hube12/DecompilerMC#24]
Not a python programmer, not sure why this is happening either. Here is what I did:

```
% python main.py                
Decompiling using official mojang mappings (Default option are in uppercase, you can just enter)
Do you want to clean up old runs? (y/N): y
Please input you decompiler choice: fernflower or cfr (CFR/f): 
Please input a valid version starting from 19w36a (snapshot) and 1.14.4 (releases),
Use 'snap' for latest snapshot (20w49a) or 'latest' for latest version (1.16.4) :latest
Please select either client or server side (C/s) : 
Downloading versions/version_manifest.json...
Downloading versions/1.16.4/version.json...
Auto Mode? (Y/n): y
Found 1.16.4.json
Downloading the mappings for 1.16.4...
Downloading mappings/1.16.4/client.txt...
Done !
Downloading versions/1.16.4/client.jar...
Done !
=== Remapping jar using SpecialSource ====
Traceback (most recent call last):
  File "main.py", line 650, in <module>
    main()
  File "main.py", line 580, in main
    remap(version, side, args.quiet)
  File "main.py", line 256, in remap
    ], check=True, capture_output=quiet)
  File "/Users/chew/anaconda3/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```

On macOS Big Sur using zsh

Is this a problem with my installation? I've no clue sadly...

**Comment by hube12** [comment]
Hi, it seems that it didn't test it enough in 3.7-, in python 3.6 capture_output didn't exists, I suggest either upgrading to a newer version or just replace at line https://github.com/hube12/DecompilerMC/blob/master/main.py#L256
```python
 ], check=True, capture_output=quiet)
```
with
```python
 ], check=True)
```

**Comment by Chew** [comment]
Ah, I can upgrade. I'll figure out how and get back to you. Not home atm

**Comment by Chew** [comment]
Yep, looks good now. Conda was holding my python version hostage, so off it goes. All is well again, thank you!
