### ISSUE TITLE
Getting error when running the tool inside GH Actions

### ISSUE THREAD

**Issue by u9g** [hube12/DecompilerMC#29]
Stack trace:
```
Error: Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:267)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:241)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:233)
	at java.util.ArrayList.add(ArrayList.java:464)
	at org.benf.cfr.reader.bytecode.analysis.opgraph.op3rewriters.Cleaner.removeUnreachableCode(Cleaner.java:59)
	at org.benf.cfr.reader.bytecode.CodeAnalyser.getAnalysisInner(CodeAnalyser.java:420)
	at org.benf.cfr.reader.bytecode.CodeAnalyser.getAnalysisOrWrapFail(CodeAnalyser.java:188)
	at org.benf.cfr.reader.bytecode.CodeAnalyser.getAnalysis(CodeAnalyser.java:126)
	at org.benf.cfr.reader.entities.attributes.AttributeCode.analyse(AttributeCode.java:96)
	at org.benf.cfr.reader.entities.Method.analyse(Method.java:397)
	at org.benf.cfr.reader.entities.ClassFile.analyseMid(ClassFile.java:906)
	at org.benf.cfr.reader.entities.ClassFile.analyseTop(ClassFile.java:797)
	at org.benf.cfr.reader.Driver.doJarVersionTypes(Driver.java:225)
	at org.benf.cfr.reader.Driver.doJar(Driver.java:109)
	at org.benf.cfr.reader.CfrDriverImpl.analyse(CfrDriverImpl.java:65)
	at org.benf.cfr.reader.Main.main(Main.java:48)
```
full logs here: https://github.com/u9g/test-2/runs/2348348062?check_suite_focus=true#step:7:13 any ideas?

**Comment by u9g** [comment]
Seems like it stalls after remapping jar 100% and wont continue no matter what I di

**Comment by hube12** [comment]
GH likely doesnt have the 1GB minimum required and 2GB preferred to run the decompiler

**Comment by u9g** [comment]
It says [here](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) that they guve 7gb of ram to runners

**Comment by hube12** [comment]
can you try to modify those two lines to use for instance 5G and 7G https://github.com/KaffinPX/DecompilerMC/blob/master/main.py#L327
https://github.com/KaffinPX/DecompilerMC/blob/master/main.py#L328

**Comment by hube12** [comment]
Also making a public runner is not possible, if you follow the license of Microsoft, you can not upload such code to public repos, you need to do so privately, my runners works perfectly btw but I am GH premium so maybe that's why

**Comment by KaffinPX** [comment]
Ok, thanks for answering us quickly.

**Comment by u9g** [comment]
Would you mind sharing your workflow yml and any modifications you made? I'm curious if maybe we have a big difference

**Comment by hube12** [comment]
> Would you mind sharing your workflow yml and any modifications you made to the core repo? I'm curious if maybe we have a big difference

I made no change to that repository else it would be public, my workflow is really similar to yours, I sadly can not share it in full since it contains some extra logic for me

**Comment by u9g** [comment]
> > Would you mind sharing your workflow yml and any modifications you made to the core repo? I'm curious if maybe we have a big difference
> 
> I made no change to that repository else it would be public, my workflow is really similar to yours, I sadly can not share it in full since it contains some extra logic for me

it's fine, thanks for trying to help

**Comment by hube12** [comment]
btw I saw that your build did succeed now with 5G 7G, I guess cfr has more trouble with newest snapshot, I will change those limit to 3 and 4 like fernflower, also please use the `--quiet` or `-q` flag to disable the press enter to exit at the end

**Comment by u9g** [comment]
oh my gosh, thanks, also is there an option to set ram used as an arg? that would be very good, for now I guess I can just make a .patch for it

**Comment by hube12** [comment]
> oh my gosh, thanks, also is there an option to set ram used as an arg? that would be very good, for now I guess I can just make a .patch for it

An args wouldn't make much sense since java will auto adjust most of the time, the main issue is that different version take different amount of ram to decompile, also since it is heavily decompiler dependant, I prefer to have it fixed
