### ISSUE TITLE
Failed to execute script main

### ISSUE THREAD

**Issue by Ascol14** [hube12/DecompilerMC#51]
Hello,

I have run main.exe with this command : main.exe --mcv latest -q
And the program return this error :
```Traceback (most recent call last):
  File "main.py", line 736, in <module>
  File "main.py", line 668, in main
  File "main.py", line 387, in decompile_cfr
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['java', '-Xmx4G', '-Xms1G', '-jar', 'D:\\decompile_minecraft\\DecompilerMC_win\\lib\\cfr-0.146.jar', 'D:\\decompile_minecraft\\DecompilerMC_win\\src\\1.19.4-client-temp.jar', '--outputdir', './src/1.19.4/client', '--caseinsensitivefs', 'true', '--silent', 'true']' returned non-zero exit status 1.
[13700] Failed to execute script main```
I don't know if the process is finished.

Have you an idea, why ?

**Comment by hube12** [comment]
Java is not installed?

**Comment by Sidiusz** [comment]
Same, Java 17 SDK\JDK installed

```
Auto Mode? (Y/n): y
Found 1.7.10.json
Traceback (most recent call last):
  File "main.py", line 652, in <module>
  File "main.py", line 579, in main
  File "main.py", line 208, in get_mappings
KeyError: 'client_mappings'
[15208] Failed to execute script main
```
